### ISSUE TITLE
Coordination structure

### ISSUE THREAD

**Issue by JulianBruns** [biggis-project/sigspatial16-paper#3]
Set up inital meetings to discuss other issues

**Comment by wipatrick** [comment]
@JulianBruns @SteinManuel @seebacherd @frank-fzi @bamfz @vsimko

My proposal for writing process (once the structure of the paper is set):
1. Every participant who is envolved in the writing process creates its **own** branch of the repo so that we don't get confused with all the different parts. Naming convention: **`<Github_account_name>`**
2. The various parts are then merged after being discussed into the **wip** branch.
3. Finally the wip branch will eventually be discussed and merged into the **master** branch which is supposed to be the camera-ready submission version of paper.

**Comment by vsimko** [comment]
Seems reasonable. I have, however, never done writing a paper this way.

As an alternative to be discussed could be:
- instead of branch-per-user, everybody forks this repo
- instead of "wip" merging, we could use pull-requests
- final submitted versions and camera-ready versions would be done through tags/releases

**Comment by wipatrick** [comment]
ok seems even better 👍  💯

**Comment by vsimko** [comment]
Since we are using the "pull request" strategy, Patrick should be the only person who has write-access to this repo and coordinates pull requests.

Please mark that you agree:
- [x] @vsimko
- [x] @wipatrick 
- [x] @JulianBruns
- [ ] @seebacherd 
- [x] @frank-fzi 
- [ ] @bamfz

**Comment by wipatrick** [comment]
ich schließe diesen Punkt.
